fix(shared): use legacyBehaviour with Link-component
YJDH-622.

Fixes <a> used as a child for Link-component:

```
Error: Invalid <Link> with <a> child. Please remove <a> or use <Link
legacyBehavior>.
Learn more:
https://nextjs.org/docs/messages/invalid-new-link-with-extra-anchor
```

LinkText-component is used by NotFound-component, so the issue occurred
everytime a user visited a page that could not be found, e.g
`http://localhost:3200/a-page-that-does-not-exist`.