Fixes to summer voucher youth UI browser tests (#3938)
* test(ks,youth): fix browser tests

HL-1661 YJDH-766.

Fix browser Kesaseteli's Youth UI browser-tests. Some of the tests are
testing integration between the youth' and the handlers' UI -- those
tests are now moved to a new file to create a new test suite for them.

Sync school list faker with current valid content.

Ignore some redundant console messages on Testcafe runs.

* fix(ks,employer): use next-i18next instad of react-i18next

HL-1661 YJDH-766.

* fix: add react-i18next as dep in kesaseteli

HL-1661 YJDH-766.

Fixing the following error in every Kesaseteli frontend after NExtJS15
upgrade.

```
⨯ [Error: Cannot find module 'react-i18next'
Require stack:
- /app/node_modules/next-i18next/dist/commonjs/index.js
- /app/kesaseteli/handler/.next/server/pages/_app.js
- /app/node_modules/next/dist/server/require.js
- /app/node_modules/next/dist/server/next-server.js
- /app/node_modules/next/dist/server/next.js
- /app/shared/src/server/next-server.js] {
code: 'MODULE_NOT_FOUND',
requireStack: [Array]
```

* style(ks,shared): fix linting issues

HL-1661 YJDH-766.

Fix issues found by running `yarn lint` to Kesäseteli apps.

* style(ks): fix linting issues

HL-1661 YJDH-766.

Fix linting issues found by running `yarn lint` on each KEsäseteli
frontend app.

* style(ks,shared): fix issues with strict typechecking

HL-1661 YJDH-766.

NextJS forces the `jsx` property in `tsconfig` to "preserve". because of
that, there were many issues, without enabling the `strict` property
too. When strict is enabled, lots of new typecheck issues were found by
running `yarn typecheck`.

* style(ks): fix typecheck issues

HL-1661 YJDH-766.

NextJS forces the `jsx` property in `tsconfig` to "preserve". because of
that, there were many issues, without enabling the `strict` property
too. When strict is enabled, lots of new typecheck issues were found by
running `yarn typecheck`.

* fix(shared): portal document usage

HL-1661 YJDH-766

* Fix Benefit frontend type checks and linting issues (#3943)

* style: set strict mode on in tsconfig

HL-1661 YJDH-766.

* style(shared): fix typecheck and linting issues

HL-1661 YJDH-766.

* style(benefit,shared): fix typecheck and linting issues

HL-1661 YJDH-766.

* style(benefit,handler): fix typecheck and linting issues

HL-1661 YJDH-766.

* style(benefit,applicant): fix typecheck and linting issues

HL-1661 YJDH-766.