HL: Rename .xlsx test filename's "ä" to "a"
Rename "Helsinki-lisä laskurin testitapaukset.xlsx" to
"Helsinki-lisa laskurin testitapaukset.xlsx" to fix Platta's Sonarcloud
test failing because of "ä" character in the filename:
 - ##[error]ERROR: Error during SonarScanner execution
   ERROR: Error during SonarScanner execution
 - ##[error]java.nio.file.InvalidPathException: Malformed input or input
   contains unmappable characters: backend/benefit/calculator/tests/
   Helsinki-lis?? laskurin testitapaukset.xlsx
 - java.nio.file.InvalidPathException: Malformed input or input contains
   unmappable characters: backend/benefit/calculator/tests/
   Helsinki-lis?? laskurin testitapaukset.xlsx

Refs YJDH-596 (This error came up in testing)