chore(ks,docker): fix compose config and scripts for Podman
YJDH-785.

Using Podman and `podman compose` failed with include-keyword, because
it could not extend the base services:

```shell
❯ yarn employer:build
yarn run v1.22.22
$ yarn employer:up --build --renew-anon-volumes
$ yarn employer up --build --renew-anon-volumes
$ cross-env COMPOSE_HTTP_TIMEOUT=200 docker compose -f
compose/employer.dev.yml up --build --renew-anon-volumes
>>>> Executing external compose provider
"/usr/local/bin/docker-compose". Please see podman-compose(1) for how to
disable this message. <<<<
```

and

```shell
❯ docker compose -f compose/employer.dev.yml config --services
>>>> Executing external compose provider
"/usr/local/bin/docker-compose". Please see podman-compose(1) for how to
disable this message. <<<<

services.backend conflicts with imported resource
Error: executing /usr/local/bin/docker-compose -f
compose/employer.dev.yml config --services: exit status 1
```

It seems that Podman is more strict and less "smart" with compose
configuration. Podman runs in the circular reference trap. Instead of
using include-keyword, an extend-keyword and/or layered command should
be used instead.

> "When Podman sees include, it treats the included file as a separate
"sub-project." If that sub-project has a service named employer, your
current file isn't allowed to have one."

NOTE: Extending a service does not "include" it's volumes and networks,
etc. Because of that, a layered command is needed to merge those
configurations in the used compose config.