fix(kesaseteli): downgrade to elasticsearch v7 to fix send_audit_log
elasticsearch was upgraded to v8 as part of PR #3157
"Upgrade Django to 4.2 & all dependencies except black/isort/flake8",

After merging that PR the quarter hourly cronjobs running send_audit_log
using `manage.py runjobs quarter_hourly` started failing:
```
ERROR OCCURED IN JOB: send_audit_log (APP: shared.audit_log)
TypeError: '<' not supported between instances of 'str' and 'int'
```

Similar Elasticsearch v7 downgrade was done for Helsinki benefit
application in PR #1942:
 - https://github.com/City-of-Helsinki/yjdh/pull/1942

refs YJDH-696 (after elasticsearch v8 upgrade audit log sending failed)