fix: add react-i18next as dep in kesaseteli
HL-1661 YJDH-766.

Fixing the following error in every Kesaseteli frontend after NExtJS15
upgrade.

```
⨯ [Error: Cannot find module 'react-i18next'
Require stack:
- /app/node_modules/next-i18next/dist/commonjs/index.js
- /app/kesaseteli/handler/.next/server/pages/_app.js
- /app/node_modules/next/dist/server/require.js
- /app/node_modules/next/dist/server/next-server.js
- /app/node_modules/next/dist/server/next.js
- /app/shared/src/server/next-server.js] {
code: 'MODULE_NOT_FOUND',
requireStack: [Array]
```