fix(docker): do not set platform in compose
YJDH-622.

Running kesaseteli-dm / postgres on Mac OS with Podman fails because
compose is setting a platform specification (to Linux).

Dokcer compose specs for that option:
https://docs.docker.com/reference/compose-file/build/#platforms.

A list of available platforms is documented here:
https://docs.docker.com/reference/compose-file/services/#platform.

- "When the platforms attribute is omitted, Compose includes the
service's platform in the list of the default build target platforms."

- "When the platforms attribute is defined, Compose includes the
service's platform, otherwise users won't be able to run images they
built."

----

Running with command:

```
podman compose -f compose.employer.yml up -d postgres --build
```

failed with

```
Error response from daemon: no such image:
docker.io/library/yjdh-kesaseteli-postgres:latest: image not known
Error: executing /usr/local/bin/docker-compose -f compose.employer.yml
up -d postgres: exit status 1
```

When the platform specification is removed from the compose file, it
succeeds.